added support for three level config search and loaded env first
LetsFocus/goLF pull request #75
Opened 2024-05-26 15:30 UTC by Himamadhuri

2024-05-26 15:56 UTC, babajikomali commented on configs/configs.go
> +	maxDepth := 3
Define both of them as constants

2024-05-26 15:58 UTC, babajikomali commented on configs/configs.go
> +	maxDepth := 3
Define maxDepth as constant

2024-05-26 16:01 UTC, babajikomali commented on configs/configs.go
> +		findConfigsDir(parentDir)
What is the base case for recursion?

2024-05-26 16:01 UTC, babajikomali commented on configs/configs.go
> +			return "", os.ErrNotExist
remove additional tab space

2024-05-26 16:02 UTC, babajikomali commented on configs/configs.go
> +				log.Error("No app_env file found")
extra tab space.

2024-05-26 16:04 UTC, babajikomali commented on configs/configs.go
> +		return Config{Log: log}
How can we return Config when we are unable to get current directory?

2024-05-26 16:05 UTC, babajikomali commented on configs/configs.go
> +	if err != nil {
remove this if condition, make the else condition as if. and add this log before return. We don't need a if else ladder here, single if is sufficient.

2024-05-26 16:06 UTC, babajikomali commented on configs/configs.go
> +			log.Error("No .env file found")
return statement?

2024-05-26 16:06 UTC, babajikomali commented on configs/configs.go
> +				log.Error("No app_env file found")
return statement?

2024-05-26 16:10 UTC, babajikomali commented on configs/configs.go
> +	depth := 0
if depth always starts from zero, there is no base condition for recursion. The depth must be passed between the recursive calls. When the depth exceeds the maxDepth it is the base condition.

2024-05-27 16:37 UTC, babajikomali commented on configs/constants.go
> +	maxDepth = 3
rename MAX_DEPTH

2024-05-27 16:39 UTC, babajikomali commented on configs/configs.go
> +		if err := godotenv.Load(appEnvPath); err != nil {
return nil

2024-05-27 16:39 UTC, babajikomali commented on configs/configs.go
>  		log.Error("No .env file found")
return nil

2024-05-27 16:39 UTC, babajikomali commented on configs/configs.go
> +		log.Infof("No configs directory found:%v", err)
return nil

2024-05-27 16:40 UTC, babajikomali commented on configs/configs.go
>  func NewConfig(log *logger.CustomLogger) Config {
return a pointer to Config instead of Config

2024-05-27 16:40 UTC, babajikomali commented on configs/configs.go
> +	if err != nil {
return nil

2024-06-09 14:57 UTC, Durga-chikkala requested changes
- Log warnings instead of errors 
- func (c *Config) GetRequired(key string) (string, error) {} 
use:
Helper function to check if a critical environment variable is set

2024-06-09 14:57 UTC, Durga-chikkala commented on configs/constants.go
> +	MAX_DEPTH = 3
give clear name and don't use _

2024-06-09 14:57 UTC, Durga-chikkala commented on configs/configs.go
> +			return "", os.ErrNotExist
don't return os errors

2024-06-09 14:57 UTC, Durga-chikkala commented on configs/configs.go
> +	return &Config{Log: log}
GetOrDefault(key, default) :   if key not exists default value will be return.

2024-06-09 14:57 UTC, Durga-chikkala commented on configs/configs.go
> +func findConfigsDir(dir string) (string, error) {
keep this function at the bottom since it is a helper function, let's keep all the helper functions at the bottom

2024-06-09 14:57 UTC, Durga-chikkala commented on configs/configs.go
> +	}
lets keep this as a seperate function and use it below as well for app_env

2024-06-30 14:08 UTC, Durga-chikkala commented on configs/configs.go
> +		log.Infof("No configs directory found: %v", err)
use error log

2024-06-30 14:08 UTC, Durga-chikkala commented on configs/configs.go
> +		log.Error(err.Error())
add log statement and use errorf

2024-06-30 14:09 UTC, Durga-chikkala commented on configs/configs.go
> +		return fmt.Errorf("failed to load main .env file")
these errors shouldn't registered

2024-06-30 16:02 UTC, Durga-chikkala approved these changes

2024-06-30 16:05 UTC, babajikomali approved these changes

2024-06-30 18:06 UTC, merged